import './globals.css';
import ApolloExtractCache from "./ApolloExtractCache";
import Provider from './ApolloProviderWrapper';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
            {children}
            {/* @ts-expect-error Server Component */}
            <ApolloExtractCache />
        </Provider>
      </body>
    </html>
  )
}
